version: '3'
services:
  admin-backend:
    restart: always
    build:
      context: ./admin-backend
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - ./admin-backend:/app
    ports:
      - '5000:5000'
  client-backend:
    build:
      context: ./client-backend
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - ./client-backend:/app
    ports:
      - '5001:5001'
  admin-frontend:
    stdin_open: true
    build:
      context: ./admin-frontend
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - ./admin-frontend:/app
    ports:
      - '3000:3000'
  client-frontend:
    stdin_open: true
    build:
      context: ./client-frontend
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - ./client-frontend:/app
    ports:
      - '3001:3000'
